# Generated by Django 3.2.5 on 2021-07-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loc_name',
            new_name='location_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
