# Generated by Django 3.2.5 on 2021-07-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_rename_image_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
